name: C Linux Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: linux

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make -C assignment1/ all
      
